# Generated by Django 5.0.4 on 2024-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_color_alter_variation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
